import type { BlueprintDocument } from "./types.js";
import { adrDocument, architectureDocument, governanceDocument, handbookDocument, moduleDocument } from "./templates.js";
export function getBlueprintRegistry(): BlueprintDocument[] {
  return [
    { relativePath: "00-governance/constitution.md", content: governanceDocument("ANW AI-COS Constitution", "Defines mission, engineering, medical safety, AI ethics, community, documentation, and release principles.") },
    { relativePath: "00-governance/vision.md", content: governanceDocument("Vision", "Defines the long-term future of ANW AI-COS.") },
    { relativePath: "00-governance/mission.md", content: governanceDocument("Mission", "Ensure no person facing Acoustic Neuroma navigates alone through trusted education, compassionate support, practical resources, and community.") },
    { relativePath: "00-governance/core-values.md", content: governanceDocument("Core Values", "Defines the values guiding product, engineering, content, and community decisions.") },
    { relativePath: "00-governance/medical-safety-policy.md", content: governanceDocument("Medical Safety Policy", "Defines safeguards and mandatory human review for medical content.") },
    { relativePath: "00-governance/ai-ethics-policy.md", content: governanceDocument("AI Ethics Policy", "Defines transparent, privacy-aware, human-supervised AI behavior.") },
    { relativePath: "01-enterprise-blueprint/01-executive-vision.md", content: architectureDocument("Executive Vision", "Explains why ANW AI-COS exists and how success is measured.") },
    { relativePath: "01-enterprise-blueprint/02-enterprise-architecture.md", content: architectureDocument("Enterprise Architecture", "Defines layers, boundaries, engines, and dependencies.") },
    { relativePath: "01-enterprise-blueprint/03-ai-agent-architecture.md", content: architectureDocument("AI Agent Architecture", "Defines AI agents, controls, and handoffs.") },
    { relativePath: "01-enterprise-blueprint/04-data-architecture.md", content: architectureDocument("Data Architecture", "Defines Supabase models, ownership, access control, storage, and audit strategy.") },
    { relativePath: "01-enterprise-blueprint/05-workflow-architecture.md", content: architectureDocument("Workflow Architecture", "Defines end-to-end content and business workflows.") },
    { relativePath: "01-enterprise-blueprint/06-engine-catalog.md", content: architectureDocument("Engine Catalog", "Catalogs all platform engines and relationships.") },
    { relativePath: "01-enterprise-blueprint/07-platform-integrations.md", content: architectureDocument("Platform Integrations", "Defines WordPress, Supabase, Make, Google Drive, GitHub, and publishing integrations.") },
    { relativePath: "01-enterprise-blueprint/08-security-architecture.md", content: architectureDocument("Security Architecture", "Defines authentication, authorization, secrets, privacy, and threat controls.") },
    { relativePath: "01-enterprise-blueprint/09-deployment-and-operations.md", content: architectureDocument("Deployment and Operations", "Defines environments, deployment, monitoring, backups, and recovery.") },
    { relativePath: "01-enterprise-blueprint/10-roadmap.md", content: architectureDocument("Enterprise Roadmap", "Defines phased development and future capabilities.") },
    { relativePath: "02-module-encyclopedia/knowledge-engine.md", content: moduleDocument("Knowledge Engine") },
    { relativePath: "02-module-encyclopedia/ai-engine.md", content: moduleDocument("AI Engine", ["Knowledge Engine"]) },
    { relativePath: "02-module-encyclopedia/prompt-library.md", content: moduleDocument("Prompt Library", ["Knowledge Engine", "AI Engine"]) },
    { relativePath: "02-module-encyclopedia/content-pipeline.md", content: moduleDocument("Content Pipeline", ["Prompt Library", "AI Engine"]) },
    { relativePath: "02-module-encyclopedia/carousel-engine.md", content: moduleDocument("Carousel Engine", ["Prompt Library", "AI Engine", "Content Pipeline"]) },
    { relativePath: "02-module-encyclopedia/image-prompt-engine.md", content: moduleDocument("Image Prompt Engine", ["Prompt Library", "Content Pipeline"]) },
    { relativePath: "02-module-encyclopedia/publishing-engine.md", content: moduleDocument("Publishing Engine", ["Content Pipeline"]) },
    { relativePath: "02-module-encyclopedia/analytics-engine.md", content: moduleDocument("Analytics Engine", ["Publishing Engine"]) },
    { relativePath: "02-module-encyclopedia/automation-engine.md", content: moduleDocument("Automation Engine", ["Content Pipeline", "Publishing Engine"]) },
    { relativePath: "02-module-encyclopedia/review-and-approval-engine.md", content: moduleDocument("Review and Approval Engine", ["Content Pipeline", "Medical Safety Policy"]) },
    { relativePath: "03-architecture-decisions/ADR-001-platform-architecture.md", content: adrDocument("001", "Platform Architecture", "Use a modular, layered architecture with documented boundaries.") },
    { relativePath: "03-architecture-decisions/ADR-002-carousel-standard.md", content: adrDocument("002", "Configurable Carousel Standard", "Support 5, 6, 8, 10, 12, and custom slide counts, with 10 as the default.") },
    { relativePath: "03-architecture-decisions/ADR-003-human-review.md", content: adrDocument("003", "Human Review Requirement", "Require human approval for medical and patient-facing content.") },
    { relativePath: "03-architecture-decisions/ADR-004-github-source-of-truth.md", content: adrDocument("004", "GitHub as Source of Truth", "Use GitHub as the authoritative source for code and technical documentation.") },
    { relativePath: "03-architecture-decisions/ADR-005-supabase-data-platform.md", content: adrDocument("005", "Supabase Data Platform", "Use Supabase as the master database and primary backend.") },
    { relativePath: "03-architecture-decisions/ADR-006-documentation-first.md", content: adrDocument("006", "Documentation First", "Require architecture and specifications before major implementation.") },
    { relativePath: "03-architecture-decisions/ADR-007-automation-first.md", content: adrDocument("007", "Automation First", "Evaluate repeatable workflows for safe automation.") },
    ...[
      ["04-engineering/README.md","Engineering Handbook","Engineering"],
      ["04-engineering/coding-standards.md","Coding Standards","Engineering"],
      ["04-engineering/git-workflow.md","Git Workflow","Engineering"],
      ["04-engineering/documentation-standards.md","Documentation Standards","Engineering"],
      ["04-engineering/development-lifecycle.md","Development Lifecycle","Engineering"],
      ["05-api/README.md","API Handbook","API"],
      ["05-api/api-design-standards.md","API Design Standards","API"],
      ["06-database/README.md","Database Handbook","Database"],
      ["06-database/rls-strategy.md","Row-Level Security Strategy","Database"],
      ["07-workflows/README.md","Workflow Handbook","Workflow"],
      ["08-design-system/README.md","Design System","Design"],
      ["09-testing/README.md","Testing Handbook","Testing"],
      ["09-testing/testing-strategy.md","Testing Strategy","Testing"],
      ["10-operations/README.md","Operations Handbook","Operations"],
      ["10-operations/incident-response.md","Incident Response","Operations"],
      ["11-releases/README.md","Release Handbook","Release"],
      ["11-releases/release-process.md","Release Process","Release"],
      ["templates/module-specification-template.md","Module Specification Template","Template"],
      ["templates/adr-template.md","ADR Template","Template"],
      ["templates/workflow-template.md","Workflow Template","Template"],
      ["templates/test-plan-template.md","Test Plan Template","Template"]
    ].map(([relativePath,title,category]) => ({ relativePath, content: handbookDocument(title, category) }))
  ];
}
