const today = () => new Date().toISOString().slice(0, 10);
const list = (items: string[]) => items.length ? items.map((x) => `  - "${x}"`).join("\n") : "  []";
export function frontmatter(title: string, documentType: string, category: string, tags: string[] = [], dependencies: string[] = []): string {
  return `---\ntitle: "${title}"\ndocumentType: "${documentType}"\nversion: "1.0.0"\nstatus: "Draft"\nowner: "AVC Advertising Services"\nproject: "ANW AI-COS"\ncreated: "${today()}"\nlastUpdated: "${today()}"\nnextReview: ""\ncategory: "${category}"\ntags:\n${list(tags)}\ndependencies:\n${list(dependencies)}\nrelatedDocuments: []\nrelatedADR: []\n---\n\n`;
}
export const section = (title: string, body = "To be completed.") => `## ${title}\n\n${body}\n\n`;
export function governanceDocument(title: string, purpose: string): string { return frontmatter(title, "Governance", "Governance", ["governance"]) + `# ${title}\n\n` + section("Purpose", purpose) + section("Policy") + section("Responsibilities") + section("Review and Approval"); }
export function architectureDocument(title: string, summary: string): string { return frontmatter(title, "Architecture Specification", "Architecture", ["architecture"]) + `# ${title}\n\n` + section("Executive Summary", summary) + section("Scope") + section("Architecture Principles") + section("Components") + section("Data Flow") + section("Dependencies") + section("Security and Privacy") + section("Failure Handling") + section("Observability") + section("Future Evolution"); }
export function moduleDocument(title: string, dependencies: string[] = []): string { return frontmatter(title, "Module Specification", "Module", ["module", "engine"], dependencies) + `# ${title}\n\n` + ["Executive Summary","Purpose","Responsibilities","Scope","Functional Requirements","Non-functional Requirements","Inputs","Outputs","Public API","Internal Components","Configuration","Error Handling","Logging and Observability","Security and Privacy","Performance","Testing","Examples","Future Roadmap"].map((x) => section(x)).join("") + section("Dependencies", dependencies.length ? dependencies.map((x) => `- ${x}`).join("\n") : "None documented.") + section("Review Checklist", "- [ ] Metadata complete\n- [ ] Purpose defined\n- [ ] Responsibilities documented\n- [ ] Interfaces identified\n- [ ] Dependencies listed\n- [ ] Error handling covered\n- [ ] Security reviewed\n- [ ] Examples included\n- [ ] Testing requirements documented\n- [ ] Approved"); }
export function adrDocument(number: string, title: string, decision: string): string { return frontmatter(`ADR-${number}: ${title}`, "Architecture Decision Record", "Decision", ["adr"]) + `# ADR-${number}: ${title}\n\n` + section("Status", "Accepted") + section("Context") + section("Decision", decision) + section("Alternatives Considered") + section("Consequences") + section("Risks") + section("Future Review Date") + section("Related Modules") + section("Related Documents"); }
export function handbookDocument(title: string, category: string): string { return frontmatter(title, "Handbook", category, ["handbook"]) + `# ${title}\n\n` + section("Purpose") + section("Standards") + section("Required Practices") + section("Prohibited Practices") + section("Checklist") + section("Examples") + section("Review and Governance"); }
